# Python runtime as a base image
FROM python:3.9-slim

# Set the working directory to /app (inside the container)
WORKDIR /app

# Copy the requirements.txt file into the container at /app
COPY banking-backend/requirements.txt .

# Install the dependencies inside the container
RUN pip install --no-cache-dir -r requirements.txt

# Copy the whole banking-backend directory into /app
COPY banking-backend/ .

# Set the entry point to run your application
CMD ["python", "secure-banking.py"]
